name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:      # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Necessário para fazer commit no repositório
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: vizwoxs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: Push to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Update snake animation" -a || echo "No changes to commit"
          git push
